### ISSUE TITLE
Update GeckoView Beta and Release on master

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/relbot#25]
We've setup relbot to open PRs to bump the GeckoView Nightly version on `master`. We need to do the same for beta and release to keep our components compiling against the latest versions and fix issues timely to avoid surprises on "merge day".

**Comment by st3fan** [comment]
@pocmo What is the upgrade rule here? Do we stick to the major version that is currently in `Gecko.kt` or do we auto upgrade to newer major versions?

**Comment by pocmo** [comment]
Yeah, it's the same for all channels, the major version is only updated on merge day.

**Comment by st3fan** [comment]
@pocmo Do we want two separate PRs to make it easier to identify problems?
