### ISSUE TITLE
Seperate version updates from geckoview updates

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/relbot#41]
We want to move to a model where GeckoView is automatically updated (frequently) periodically on A-C release branches, but where actual version bumps and releases are created on a slower fixed schedule.

 - Pull in new GV versions to release branches every 30 minutes
 - Check if there is a need to create a release only once or twice a day on a predictable (documented) schedule
 
This will have some nice side effects:

 - There will be fewer dot releases, since multiple changes can be bundled in a single release
 - There is less (no?) change of conflicting version bumps since instead of doing this with every GV update, it is not done once a day by a separate process.
 - We can take advantage of this for uplifts: "if you land this before 3pm EST, it will automatically go out in a new release"
 
In case we need more control, we can always use Ship-It for A-C to create a new release at any point in time.

Changes that we will need to make:

 - Simply the `_update_geckoview()` to not call `_update_ac_version()` anymore.
 - Introduce either a new command or integrate version bumps into the `create-release` task

**Comment by rvandermeulen** [comment]
I don't think we need this anymore now that AC releases are in Ship-It.
