### ISSUE TITLE
Start using new style release branch names for A-C

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/relbot#51]
Instead of `releases/123.0` we should switch to the format that our other tooling expects: `releases_123.0`

@escapewindow Is it ok to just replace the `/` with `_`? Fenix format is `releases_v85.0.0` (extra `.0` and `v`) - we can also follow that for consistency.

This will also need an update in the A-C release process docs and communication to the team.

**Comment by st3fan** [comment]
@pocmo can you think of anything that may fail if we change the release branch name?

**Comment by escapewindow** [comment]
@st3fan reading https://bugzilla.mozilla.org/show_bug.cgi?id=1680064 , I think replacing `/` with `_` should work.
I suspect the `master/.../...` branches that we're using for PRs may also be confusing things.

**Comment by escapewindow** [comment]
Mergify also uses `/` in branch names: https://github.com/mozilla-releng/scriptworker/issues/477#issuecomment-761080815

**Comment by pocmo** [comment]
> @pocmo can you think of anything that may fail if we change the release branch name?

The only thing I can think of are the branch protection rules and potentially mergify rules.

**Comment by escapewindow** [comment]
We want a change like #45 .

**Comment by jcristau** [comment]
This was done.
