### ISSUE TITLE
Relbot should not create a new branch for every AC update

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/relbot#71]
In Fenix (using MickeyMoz), the update PR re-uses the same branch `ac-update`, see: https://github.com/mozilla-mobile/fenix/pull/22624

We should do something similar with relbot or perform some cleanup task after the PR is merged so that the stale branches are removed from the project.

**Comment by rvandermeulen** [comment]
This looks like a dupe of #32 if I'm not mistaken.
